const Courses = [
  {
    id: "1",
    title: 'Web Development',
    img: require('../assets/web.jpg'),
    descripation: 'Web development is the work involved in developing a website for the Internet or an intranet.',
    course1: 'HTML',
    course2: 'CSS',
    course3: 'JavaScript',
    price: '$ 5000',
  },
  {
    id: "2",
    title: 'Graphic design',
    img: require('../assets/graphic.jpg'),
    descripation: 'Graphic design is the profession and academic discipline whose activity consists in projecting visual communications .',
    course1: 'Photoshop',
    course2: 'Figma',
    course3: 'Adobe XD',
    price: '$ 3000',
  },
  {
    id: "3",
    title: 'Ethical Hacking',
    img: require('../assets/ethical.jpg'),
    descripation: 'The Ethical Hacking course will help you master skills such as footprinting, session hijacking, cryptography.',
    course1: 'Testing',
    course2: 'Exploitation',
    course3: 'Linux OS',
    price: '$ 6000',
  }, {
    id: "4",
    title: 'Web design',
    img: require('../assets/web1.jpg'),
    descripation: 'Web design encompasses many different skills and disciplines.',
    course1: 'HTML',
    course2: 'CSS',
    course3: 'JavaScript',
    price: `$ 8000`,
  },
  {
    id: "5",
    title: 'Web Development',
    img: require('../assets/web.jpg'),
    descripation: 'Web development is the work involved in developing a website for the Internet or an intranet.',
    course1: 'HTML',
    course2: 'CSS',
    course3: 'JavaScript',
    price: '$ 5000',
  },
]
export default Courses;
